### PR TITLE
Fix for #78

### PR DESCRIPTION
**Pull request by adambiggs**
Added some stricter type checking to avoid throwing errors in the constructor, and restore previous behaviour from before a08f7794f802fcc184ddff857e4786cc9ebd2aab.

### CODE REVIEW

**Comment by gf3** [comment]
:+1: amazing

**Comment by gf3** [comment]
thank you

**Comment by gf3** [comment]
@adambiggs released in [2.0.1](https://github.com/gf3/moment-range/releases/tag/2.0.1)

**Comment by adambiggs** [comment]
Nice, that was fast! :beers:

**Pull request merged**
