### PR TITLE
add .toArray, closes #95

### LINKED ISSUE #95: .toArray
I think a `toArray` convenience method would be useful. Quite often one needs to have the range as array and work with it later, not iterating over it right away.

```js
function toArray(by) {
  by = by || 'days';
  var acc = [];
  this.by(by, function(unit) {
    acc.push(unit);
  });
  return acc;
}
```

### PR DESCRIPTION
**Pull request by tb**

### CODE REVIEW

**Comment by gf3** [comment]
hi @tb thanks for the PR and especially the tests, before i merge this can i bug you to add a tiny section in the README about this new method?

**Comment by tb** [comment]
@gf3 done, see https://github.com/tb/moment-range/tree/toArray#toarray

**Comment by krainboltgreene** [comment]
Any chance this could get merged?

**Comment by gf3** [comment]
merged and released in [`2.2.0`](https://github.com/gf3/moment-range/releases/tag/2.2.0)

**Comment by kenjiru** [comment]
Good job guys! I was looking for this.

**Pull request merged**
