### PR TITLE
Include border dates feature.

### PR DESCRIPTION
**Pull request by YagoQuinoy**
Boolean parameter in overlaps, intersect, add functions and more to include/exclude border dates like contains function do.

### CODE REVIEW

**Comment by TrejGun** [comment]
+1

**Comment by phpdude** [comment]
+1

**Comment by epsyl** [comment]
+1

**Comment by Koshub** [comment]
:+1:

**Comment by studentIvan** [comment]
:+1: +1

**Comment by TrejGun** [comment]
@YagoQuinoy can you please update your pr?

**Comment by TrejGun** [comment]
everybody how are interested in range borders please take a look at my fork
https://github.com/TrejGun/moment-range

**Comment by TrejGun** [comment]
@gf3 May be you can merge this into 3.0?

**Comment by gf3** [comment]
closing in favour of #144

**Pull request closed without merging**
